// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDoAn.Data;

#nullable disable

namespace QuanLyDoAn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508070700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuanLyDoAn.Models.DeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CongNgheSuDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTaDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SinhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DeTais");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoMon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongSinhVienDangHuongDan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KhoaHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.TienDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeTaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileMinhChung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhanXetCuaGiangVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDungDaLam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhanTramHoanThanh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeTaiId");

                    b.ToTable("TienDos");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DeTai", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.GiangVien", "GiangVien")
                        .WithMany("DeTaisHuongDan")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("QuanLyDoAn.Models.SinhVien", "SinhVien")
                        .WithMany("DeTais")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.GiangVien", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.User", "User")
                        .WithOne("GiangVien")
                        .HasForeignKey("QuanLyDoAn.Models.GiangVien", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.User", "User")
                        .WithOne("SinhVien")
                        .HasForeignKey("QuanLyDoAn.Models.SinhVien", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.TienDo", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.DeTai", "DeTai")
                        .WithMany("TienDos")
                        .HasForeignKey("DeTaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DeTai", b =>
                {
                    b.Navigation("TienDos");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.GiangVien", b =>
                {
                    b.Navigation("DeTaisHuongDan");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.SinhVien", b =>
                {
                    b.Navigation("DeTais");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.User", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
