// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDoAn.Data;

#nullable disable

namespace QuanLyDoAn.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511065716_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuanLyDoAn.Models.DeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CongNgheSuDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DiemHoiDong")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiemHuongDan")
                        .HasColumnType("REAL");

                    b.Property<double?>("DiemPhanBien")
                        .HasColumnType("REAL");

                    b.Property<int?>("DotDoAnId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileBaoCao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileSlide")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileSourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HoiDongId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkDemo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkGitHub")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LyDoTuChoi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTaDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SinhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DotDoAnId");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HoiDongId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DeTais");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DiemHoiDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeTaiId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DiemBaoCao")
                        .HasColumnType("REAL");

                    b.Property<double>("DiemSanPham")
                        .HasColumnType("REAL");

                    b.Property<double>("DiemThuyetTrinh")
                        .HasColumnType("REAL");

                    b.Property<double>("DiemTraLoiCauHoi")
                        .HasColumnType("REAL");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoiDongId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeTaiId");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HoiDongId");

                    b.ToTable("DiemHoiDongs");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DotDoAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaKhoa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangMoDangKy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HanDangKyDeTai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HanNopBaoCao")
                        .HasColumnType("TEXT");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiDot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DotDoAns");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoMon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GioiHanDeTai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GioiHanSinhVien")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongSinhVienDangHuongDan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.HoiDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaKhoa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DotDoAnId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHoiDong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DotDoAnId");

                    b.ToTable("HoiDongs");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.HoiDongThanhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoiDongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HoiDongId");

                    b.ToTable("HoiDongThanhViens");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.LichBaoVe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeTaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HoiDongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhongBaoVe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianBaoVe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeTaiId");

                    b.HasIndex("HoiDongId");

                    b.ToTable("LichBaoVes");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.LichGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayGioGap")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("LichGaps");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KhoaHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.TienDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeTaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileMinhChung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhanXetCuaGiangVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDungDaLam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhanTramHoanThanh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenCongViec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeTaiId");

                    b.ToTable("TienDos");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DeTai", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.DotDoAn", "DotDoAn")
                        .WithMany("DeTais")
                        .HasForeignKey("DotDoAnId");

                    b.HasOne("QuanLyDoAn.Models.GiangVien", "GiangVien")
                        .WithMany("DeTaisHuongDan")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("QuanLyDoAn.Models.HoiDong", "HoiDong")
                        .WithMany("DeTaisDuocCham")
                        .HasForeignKey("HoiDongId");

                    b.HasOne("QuanLyDoAn.Models.SinhVien", "SinhVien")
                        .WithMany("DeTais")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("DotDoAn");

                    b.Navigation("GiangVien");

                    b.Navigation("HoiDong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DiemHoiDong", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.DeTai", "DeTai")
                        .WithMany()
                        .HasForeignKey("DeTaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoAn.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoAn.Models.HoiDong", "HoiDong")
                        .WithMany()
                        .HasForeignKey("HoiDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");

                    b.Navigation("HoiDong");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.GiangVien", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.User", "User")
                        .WithOne("GiangVien")
                        .HasForeignKey("QuanLyDoAn.Models.GiangVien", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.HoiDong", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.DotDoAn", "DotDoAn")
                        .WithMany()
                        .HasForeignKey("DotDoAnId");

                    b.Navigation("DotDoAn");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.HoiDongThanhVien", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoAn.Models.HoiDong", "HoiDong")
                        .WithMany("ThanhViens")
                        .HasForeignKey("HoiDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HoiDong");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.LichBaoVe", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.DeTai", "DeTai")
                        .WithMany()
                        .HasForeignKey("DeTaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoAn.Models.HoiDong", "HoiDong")
                        .WithMany("LichBaoVes")
                        .HasForeignKey("HoiDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");

                    b.Navigation("HoiDong");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.LichGap", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDoAn.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.User", "User")
                        .WithOne("SinhVien")
                        .HasForeignKey("QuanLyDoAn.Models.SinhVien", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.TienDo", b =>
                {
                    b.HasOne("QuanLyDoAn.Models.DeTai", "DeTai")
                        .WithMany("TienDos")
                        .HasForeignKey("DeTaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DeTai", b =>
                {
                    b.Navigation("TienDos");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.DotDoAn", b =>
                {
                    b.Navigation("DeTais");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.GiangVien", b =>
                {
                    b.Navigation("DeTaisHuongDan");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.HoiDong", b =>
                {
                    b.Navigation("DeTaisDuocCham");

                    b.Navigation("LichBaoVes");

                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.SinhVien", b =>
                {
                    b.Navigation("DeTais");
                });

            modelBuilder.Entity("QuanLyDoAn.Models.User", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
